config/routes.rb
Rails.application.routes.draw do
  resources :links
  devise_for :users
  root 'links#new'
  get '/dashboard', to: 'dashboard#index'
  
  get '/:short_url', to: 'links#redirect_to_original', as: :redirect_to_original
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :user, optional: true

  validates :url, presence: true
  validates :visits, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  validates :category, presence: true, on: :update

  before_create :generate_short_url
  before_validation :set_default_visits

  private

  def generate_short_url
    newid = Link.last ? Link.last.id + 1 : 1
    self.url_short = Base64.encode64(newid.to_s).strip
  end

  def set_default_visits
    self.visits ||= 0
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: %i[show edit update destroy]
  before_action :authenticate_user!, only: %i[index edit update destroy]

  # GET /links or /links.json
  def index
    @links = Link.all
  end

  # GET /links/1 or /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = Link.new
  end
  
  # GET /links/1/edit
  def edit
  end

  # POST /links or /links.json
  def create
    if !valid_url?(link_params["url"])
      flash[:alert] = "Niepoprawny URL, przekierowano na stronę główną."
      redirect_to root_path and return
    end

    @link = Link.new(link_params)
    @link.user = current_user if user_signed_in?
    @link.user_id = current_user ? current_user.id : 1


    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1 or /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to link_url(@link), notice: "Link was successfully updated." }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1 or /links/1.json
  def destroy
    @link.destroy

    respond_to do |format|
      format.html { redirect_to links_url, notice: "Link was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def redirect_to_original
    @link = Link.find_by(url_short: params[:short_url]+"==")
    if @link
      redirect_to @link.url, allow_other_host: true
    else
      # Dodaj obsługę przypadku, gdy skrócony link nie istnieje
      render plain: 'Skrócony link nie istnieje', status: :not_found
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def link_params
      params.require(:link).permit(:url, :url_short, :category)
    end

    def valid_url?(url)
      url_pattern = /\A#{URI::DEFAULT_PARSER.make_regexp}\z/
      url =~ url_pattern
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/dashboard/index.html.erb
<h1>Dashboard#index</h1>
<p>Find me in app/views/dashboard/index.html.erb</p>


<% if current_user %>
    <h2>Hi, <%= current_user.email %>! You are logged in!</h2>
    <%= button_to "Logout", destroy_user_session_path, method: :delete %>
<% else %>

<% end %>

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Your Link Shortener</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: "layouts/alerts" %>
    <%= yield %>
  </body>
</html>

app/views/links/_form.html.erb
<%= form_with(model: link) do |form| %>
  <% if link.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
        <% link.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :url, style: "display: block" %>
    <%= form.text_field :url %>
  </div>

  <% if current_user %>
    <div>
      <%= form.label :url_short, style: "display: block" %>
      <%= form.text_field :url_short %>
    </div>
  <% end %>

  <% if action_name == 'edit' %>
    <div>
      <%= form.label :category, style: "display: block" %>
      <%= form.text_field :category %>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/links/_link.html.erb
<div id="<%= dom_id link %>">
  <p>
    <strong>User:</strong>
    <%= link.user_id %>
  </p>

  <p>
    <strong>Url:</strong>
    <%= link.url %>
  </p>

  <p>
    <strong>Url short:</strong>
    <%= link.url_short.chomp('==') %>
  </p>

  <p>
    <strong>Visits:</strong>
    <%= link.visits %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= link.category %>
  </p>

</div>

app/views/links/edit.html.erb
<h1>Editing link</h1>

<%= render "form", link: @link %>

<br>

<div>
  <%= link_to "Show this link", @link %> |
  <%= link_to "Back to links", links_path %>
</div>

app/views/links/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Links</h1>

<div id="links">
  <% @links.each do |link| %>
    <%= render link %>
    <p>
      <%= link_to "Show this link", link %>
    </p>
  <% end %>
</div>

<%= link_to "New link", new_link_path %>

app/views/links/new.html.erb
<h1>New link</h1>

<%= render "form", link: @link %>

<br>

<div>
  <%= link_to "Back to links", links_path %>
</div>

app/views/links/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @link %>

<div>
  <%= link_to "Back to links", links_path %>
  
  <% if current_user %>
    <%= link_to "Edit this link", edit_link_path(@link) %> |
    <%= button_to "Destroy this link", @link, method: :delete %>
  <% end %>
</div>